package Model;
import java.util.Random;

/**
 * <b>Wheel</b> handles the random number generation aspect of That's Life.
 * <p>
 * This class generates a random integer from 1 to 10 and returns it for the
 * game instance to use. This utilizes the <b>Random</b> class to accomplish this.
 *
 * @author  Joshue Salvador A. Jadie
 * @author  Andre Dominic H. Ponce
 * @version %I%, %G%
 */

public class Wheel
{
    /**
     * Stores the generated random number.
     */
    private int number;
    /**
     * Random instance used to generate random integers.
     */
    private Random randomizer;

    /**
     * The sole constructor of this class. Allocates a new Wheel
     * object (creates a new wheel).
     */
    public Wheel ()
    {
        number = 1;
        randomizer = new Random ();
    }

    /**
     * Generates a random integer from 1 to 10 using the Random class.
     */
    public void spin ()
    {
        number = randomizer.nextInt (10) + 1;
    }

    /**
     * Returns the random integer generated by this class.
     *
     * @return  a randomly generated integer
     */
    public int getNumber ()
    {
        return number;
    }
}
